// Precompute, for each daily number, the first salt whose challenge the PRO bot can win comfortably.
// Output: src/sim/dailyTable.ts (so every browser gets the same, verified challenge).
import { writeFileSync } from 'node:fs';
import { Bot, SKILL_PRO } from '../src/sim/bot';
import { DAILY_EPOCH, makeDaily } from '../src/sim/daily';
import { Sim } from '../src/sim/world';

const DAYS = Number(process.argv[2] ?? 400);
const salts: number[] = [];
const t0 = Date.now();
for (let n = 1; n <= DAYS; n++) {
  const date = new Date(DAILY_EPOCH + (n - 1) * 86400000 + 12 * 3600000);
  const local = new Date(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), 12);
  let chosen = 0;
  for (let salt = 0; salt < 8; salt++) {
    const d = makeDaily(local, salt);
    const sim = new Sim(d.def, d.opts);
    const bot = new Bot(sim, SKILL_PRO);
    let st = 0;
    while (sim.state === 'play' && st < 60 * 400) {
      sim.step(bot.update());
      sim.events.length = 0;
      st++;
    }
    if (sim.result?.win && sim.result.saved >= 0.6) {
      chosen = salt;
      break;
    }
    chosen = salt + 1;
  }
  salts.push(Math.min(chosen, 7));
}
writeFileSync('src/sim/dailyTable.ts', `// Generated by tools/daily-table.ts — do not edit.\nexport const DAILY_SALTS = ${JSON.stringify(salts)};\n`);
console.log(`done ${DAYS} days in ${((Date.now() - t0) / 1000).toFixed(1)}s; salt histogram`, salts.reduce((h: Record<number, number>, s) => ((h[s] = (h[s] ?? 0) + 1), h), {}));
